name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install sbcl info install-info curl
      - name: install quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --disable-debugger --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))" --eval "(sb-ext:exit)"
      - name: build-stumpwm
        run: |
          cd ${GITHUB_WORKSPACE}
          ./autogen.sh
          ./configure
          make stumpwm
